version: '3.7'

services:
  application:
    build: .
    restart: always
    ports:
      - 8080:8080
    links:
      - mysql:database
  mysql:
    image: mysql
    volumes:
      # Define um volume interno do Docker para persistir os dados
      - my-db:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

volumes:
  my-db: